export enum ConfigEnum {
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_DATABASE = 'DB_DATABASE',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_SYNC = 'DB_SYNC',

  SECRET = 'SECRET',

  SYSTEM_PROMPT = 'SYSTEM_PROMPT',
  NORMALIZE_SYSTEM_PROMPT = 'NORMALIZE_SYSTEM_PROMPT',
}

export enum LogEnum {
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_ON = 'LOG_ON',
  TIMESTAMP = 'TIMESTAMP',
}
