name: Docker Build and Push

on:
  push:
    branches:
      - master
    paths:
      - 'server/**' # 只有当server目录有变更时才触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile.app
          push: true
          platforms: linux/amd64
          tags: |
            dvlindev/vector-server:latest
            dvlindev/vector-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
